### PR TITLE
סוגריים

### PR DESCRIPTION
**Pull request by SalehKa**

### CODE REVIEW

**Comment by gur111** [comment]
Please fix conflicts. Also, I need to be able to clone your repository to make sure the code compiles

**Review by gur111 — CHANGES_REQUESTED** [review]
Resolve conflicts and allow public access to your fork

**Comment by SalehKa** [comment]
> Resolve conflicts and allow public access to your fork

There are no conflicts at this file, only the changes that I meant to make,
I sent you an invititation to be a collaborator in my fork, does that work or do I need to make it public?

**Comment by gur111** [comment]
> > Resolve conflicts and allow public access to your fork
> 
> There are no conflicts at this file, only the changes that I meant to make,
> I sent you an invititation to be a collaborator in my fork, does that work or do I need to make it public?

You need to make it public. I can't merge it otherwise. I think if it got to the point of being private it's not a fork but a full duplicate. So merging might not even be possible.

**Comment by gur111** [comment]
See if it tells you that the repository is unknown:

**Comment by yossigil** [comment]
I am sorry, but the dev version has converged, and there are still conflicts. Can you please create a new PR with respect to the current dev version.

**Pull request closed without merging**
